from flask import Flask
from flask_session import Session

app = Flask(__name__)
app.config["SESSION_PERMANENT"] = False
app.config["SESSION_TYPE"] = "filesystem"
Session(app)

# Dirs
SCHEMAS_DIR = "schemas"

# Tables
USER_TABLE = "Users"
USER_TOKEN_TABLE = "UserTokens"

# Files
DATABASE = "data.db"
INITIAL_SCHEMA = "initial.sql"

# Titles

USERNAME_TITLE = "username"
TOKEN_TITLE = "token"

# Permission index aliases
OPERATOR_PERMID = 1

GUEST_PERMID = 2

GUEST_REGISTER_PERMID = 3
GUEST_LOGIN_PERMID = 4

ACCOUNT_PERMID = 5

ACCOUNT_DELETE_PERMID = 6
ACCOUNT_EDIT_PERMID = 7
ACCOUNT_VIEW_PERMID = 8

REPOSITORIES_PERMID = 9

REPOSITORIES_AUTHORITY_SYSTEM_PERMID = 10

AUTHORITY_SYSTEM_DELETE_PERMID = 11
AUTHORITY_SYSTEM_EDIT_PERMID = 12
AUTHORITY_SYSTEM_VIEW_PERMID = 13

AUTHORITY_SYSTEM_TESTS_PERMID = 14

AUTHORITY_SYSTEM_TESTS_DELETE_PERMID = 15
AUTHORITY_SYSTEM_TESTS_EDIT_PERMID = 16
AUTHORITY_SYSTEM_TESTS_VIEW_PERMID = 17